# Generated by Django 2.2.16 on 2021-08-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20210812_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='titles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='reviews.Title'),
        ),
    ]
